theme:
    switch: true
    default: style-light
favicon:
    #logo: 
    visibilitychange: true
    hidden: failure.ico
    showText: (/≧▽≦/)嘿嘿，欢迎回来
    hideText: 你干啥去QAQ
user:
    name: Dawn
    email: 1934457189@qq.com
    domain: https://dawneter.github.io/
    avatar: /img/avatar.jpg
    describe: 
top_bars:
    - title: home
      url: /
      children:
    - title: archives
      url: /archives/
      noswup: true
    - title: links
      url: /links/
      noswup: true
sidebar:
    social: 
    typedText: ["a middle school student"]
    info: # 个人信息
        - key: 地址
          val: 宇宙
        - key: 年龄
          val: 16
lazyload:
    enable: true
banner:
    index:
        type: img
        bgurl: /img/dawn.jpg
        bannerTitle: 愿神明偏爱，<br>一切从欢
        bannerText: 欢迎，我的朋友!
footer:
  powered:
    enable: true
  beian:
    enable: false
    icp: 
  copyrightYear:
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 06/15/2023 17:10:48
  custom_text:
toc:
    enable: true
    list_number: true
    max_depth: 3
    min_depth: 1
post_pagination:
    enable: true
    type: small 
highlight:
    theme: true
    title: default
    copy: true
    lang: true
    code_word_wrap: true
    height_limit: 200 # 超出时，显示折叠按钮
datetime_foramt:
    post_card:
        date: YY/MM/DD
        time: HH:mm
    post_info:
        date: MM/DD
        time: HH:mm
    archive:
        date: MM/DD
        time: HH:mm
rightside:
    readmode: true
    aside: true
wordcount:
  enable: true
  count: true
  time: true






